openapi: 3.0.3
info:
  title: Query Service Authorization API
  description: >
      The Query Service Authorization API enables you to manage IP-based access restrictions for Adobe Experience Platform's Query Service, ensuring secure data access based on allowed IP ranges.
  version: 1.0.0

servers: 
  - url: https://{environment}.adobe.io/
    variables:
      environment:
        default: platform
        enum: 
          - platform
          - platform-stage

tags: 
  - name: (NEW) Interactive API documentation
    description: > 
      You can now interact with the Experience Platform API endpoints directly from this API reference page. Get your 
      [authentication credentials](http://www.adobe.com/go/platform-api-authentication-en) and use the **Try it** 
      functionality in the right rail. Note that by using this functionality, you are making real API calls. Keep this 
      in mind when you interact with production sandboxes.

  - name: IP Access
    description: > 
      Use the IP Access endpoints to manage allowed IP ranges, enabling secure data access for Query Service in Adobe Experience Platform.

  - name: IP Validation
    description: >
      Use the IP Validation endpoint to verify if a specified IP address is permitted to access data within a designated sandbox in Query Service. 

paths: 
  /security/ip-access:
    get: 
      tags: 
        - IP Access
      summary: Retrieve all allowed IP ranges for a sandbox
      operationId: retrieveIPRanges
      parameters: 
        - $ref: '#/components/parameters/authorization'
        - $ref: '#/components/parameters/x-gw-ims-org-id'
        - $ref: '#/components/parameters/x-api-key'
        - $ref: '#/components/parameters/x-sandbox-name'
      responses: 
        200:
          x-summary: "Success"
          description: "Returns a list of the sandbox’s allowed IP ranges."
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/allowedIPRangeResponse"

    put:
      tags: 
        - IP Access
      summary: Set new allowed IP ranges for a sandbox
      operationId: setIPRanges
      parameters: 
        - $ref: '#/components/parameters/authorization'
        - $ref: '#/components/parameters/x-gw-ims-org-id'
        - $ref: '#/components/parameters/x-api-key'
        - $ref: '#/components/parameters/x-sandbox-name'
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                ipRanges:
                  type: array
                  description: "List of IP ranges to allow for data access in the sandbox."
                  items:
                    type: object
                    properties:
                      ipRange:
                        type: string
                        description: "Allowed IP or CIDR range."
                        example: "136.23.110.0/23"
                      description:
                        type: string
                        description: "Optional description of the IP range."
                        example: "VPN-1 gateway IPs"
      responses: 
        200:
          x-summary: "Success"
          description: "Returns details of the newly configured IP ranges."
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/allowedIPRangeResponse"

    delete:
      tags: 
        - IP Access
      summary: Delete all configured IP ranges for a sandbox
      operationId: deleteIPRanges
      parameters: 
        - $ref: '#/components/parameters/authorization'
        - $ref: '#/components/parameters/x-gw-ims-org-id'
        - $ref: '#/components/parameters/x-api-key'
        - $ref: '#/components/parameters/x-sandbox-name'
      responses: 
        200:
          x-summary: "Success"
          description: "Returns details of the deleted IP ranges."
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/deletedIPRangeResponse"

  /security/validate/ip-access:
    post:
      tags: 
        - IP Validation
      summary: Validate IP access for a sandbox
      operationId: validateIPAddress
      parameters: 
        - $ref: '#/components/parameters/authorization'
        - $ref: '#/components/parameters/x-gw-ims-org-id'
        - $ref: '#/components/parameters/x-api-key'
        - $ref: '#/components/parameters/x-sandbox-name'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ipAddress:
                  type: string
                  description: "IP address to be validated for sandbox access."
                  example: "197.2.0.2"
      responses: 
        200:
          x-summary: "Success"
          description: "Returns a boolean indicating whether the IP is allowed to access the sandbox."
          content:
            application/json:
              schema: 
                type: object
                properties:
                  isAllowed:
                    type: boolean
                    description: >
                      Indicates whether the specified IP address is permitted to access the sandbox.
                      Returns `true` if access is allowed, and `false` otherwise.
                    example: true

components: 
  schemas:
    allowedIPRangeResponse:
      type: object
      properties:
        imsOrg:
          type: string
          description: "Organization ID associated with the sandbox."
          example: "{ORG_ID}"
        sandboxName:
          type: string
          description: "Name of the sandbox where IP restrictions are applied."
          example: "prod"
        channel:
          type: string
          description: >
            The access mode for IP restrictions. Currently, the only accepted value is `data_distiller`, which applies restrictions to PSQL and JDBC connections.
          example: "data_distiller"
        allowedIpRanges:
          type: array
          description: "List of permitted IP ranges in either CIDR or fixed IP format."
          items:
            type: object
            properties:
              ipRange:
                type: string
                description: "Allowed IP address or CIDR range."
                example: "136.23.110.0/23"
              description:
                type: string
                description: "Optional description of the IP range."
                example: "VPN-1 gateway IPs"

    deletedIPRangeResponse:
      type: object
      properties:
        imsOrg:
          type: string
          description: "Organization ID associated with the sandbox."
          example: "{ORG_ID}"
        sandboxName:
          type: string
          description: "Name of the sandbox from which IP ranges are deleted."
          example: "prod"
        channel:
          type: string
          description: >
            The access mode for IP restrictions. Currently, the only accepted value is `data_distiller`, which applies restrictions to PSQL and JDBC connections.
          example: "data_distiller"
        deletedIpRanges:
          type: array
          description: "List of deleted IP ranges."
          items:
            type: object
            properties:
              ipRange:
                type: string
                description: "Deleted IP address or CIDR range."
                example: "136.23.110.0/23"
              description:
                type: string
                description: "Description of the deleted IP range."
                example: "VPN-1 gateway IPs"

  parameters: 
    authorization:
      name: Authorization
      in: header
      description: "Bearer token for authorization."
      required: true
      schema:
        type: string
    x-gw-ims-org-id:
      name: x-gw-ims-org-id
      in: header
      description: "Organization ID for Adobe Experience Platform."
      required: true
      schema:
        type: string
    x-api-key:
      name: x-api-key
      in: header
      description: "API key for Adobe Experience Platform."
      required: true
      schema:
        type: string
    x-sandbox-name:
      name: x-sandbox-name
      in: header
      description: "Name of the sandbox where the operation will take place."
      required: true
      schema:
        type: string
